name: GitHub Packages

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Publish to GitHub Packages
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: albert221/mpra/mpra
        registry: docker.pkg.github.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
